# Generated by Django 3.1.4 on 2021-07-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(upload_to='uploaded_plant_images')),
                ('disease_identified', models.CharField(editable=False, max_length=100)),
            ],
            options={
                'verbose_name': 'Plant',
                'verbose_name_plural': 'Plants',
                'ordering': ('-created_at',),
            },
        ),
    ]
